In [1]:
import pandas as pd
import numpy as np
import urllib.request as url
import json

In [2]:
res = url.urlopen('https://data.covid19india.org/states_daily.json')
data = json.load(res)

In [3]:
type(data)

dict

In [4]:
states = data['states_daily']

In [5]:
df = pd.DataFrame(states)

In [6]:
df.head()

an ap ar as br ch ct       date     dateymd dd  ... sk     status tg tn tr  \
0  0  1  0  0  0  0  0  14-Mar-20  2020-03-14  0  ...  0  Confirmed  1  1  0   
1  0  0  0  0  0  0  0  14-Mar-20  2020-03-14  0  ...  0  Recovered  0  0  0   
2  0  0  0  0  0  0  0  14-Mar-20  2020-03-14  0  ...  0   Deceased  0  0  0   
3  0  0  0  0  0  0  0  15-Mar-20  2020-03-15  0  ...  0  Confirmed  2  0  0   
4  0  0  0  0  0  0  0  15-Mar-20  2020-03-15  0  ...  0  Recovered  1  0  0   

   tt un  up ut wb  
0  81  0  12  0  0  
1   9  0   4  0  0  
2   2  0   0  0  0  
3  27  0   1  0  0  
4   4  0   0  0  0  

[5 rows x 42 columns]

In [7]:
df.columns

Index(['an', 'ap', 'ar', 'as', 'br', 'ch', 'ct', 'date', 'dateymd', 'dd', 'dl',
       'dn', 'ga', 'gj', 'hp', 'hr', 'jh', 'jk', 'ka', 'kl', 'la', 'ld', 'mh',
       'ml', 'mn', 'mp', 'mz', 'nl', 'or', 'pb', 'py', 'rj', 'sk', 'status',
       'tg', 'tn', 'tr', 'tt', 'un', 'up', 'ut', 'wb'],
      dtype='object')

In [15]:
df['tt'] = df['tt'].astype('int')

In [16]:
confirmed_df = df[df['status'] == 'Confirmed']

In [26]:
totalCases = confirmed_df['tt'].values

In [27]:
totalCases[:10]

array([ 81,  27,  15,  11,  37,  27,  58,  78,  67, 102])

In [36]:
start = 0
end = 4
X = []
y = []
for i in range(len(totalCases) - 4):
    X.append(totalCases[start:end])
    y.append(totalCases[end])
    start += 1
    end += 1

In [37]:
X[:5]

[array([81, 27, 15, 11]),
 array([27, 15, 11, 37]),
 array([15, 11, 37, 27]),
 array([11, 37, 27, 58]),
 array([37, 27, 58, 78])]

In [38]:
y[:5]

[37, 27, 58, 78, 67]

In [39]:
len(X)

517

In [40]:
len(y)

517