In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('covid_data.csv')

In [3]:
df.shape

(2499, 12)

In [4]:
df.head()

Country  Age       Gender  fever  Bodypain  Runny_nose  \
0               China   10         Male    102         1           0   
1               Italy   20         Male    103         1           1   
2                Iran   55  Transgender     99         0           0   
3  Republic of Korean   37       Female    100         0           1   
4              France   45         Male    101         1           1   

   Difficulty_in_breathing  Nasal_congestion  Sore_throat  Severity  \
0                        0                 0            1      Mild   
1                        0                 0            0  Moderate   
2                        0                 1            1    Severe   
3                        1                 0            0      Mild   
4                        1                 1            0  Moderate   

  Contact_with_covid_patient  Infected  
0                         No         0  
1                  Not known         1  
2                         No         0  
3                        Yes         1  
4                        Yes         1

In [5]:
df.drop(columns=['Country'], inplace=True)

In [6]:
df.head()

Age       Gender  fever  Bodypain  Runny_nose  Difficulty_in_breathing  \
0   10         Male    102         1           0                        0   
1   20         Male    103         1           1                        0   
2   55  Transgender     99         0           0                        0   
3   37       Female    100         0           1                        1   
4   45         Male    101         1           1                        1   

   Nasal_congestion  Sore_throat  Severity Contact_with_covid_patient  \
0                 0            1      Mild                         No   
1                 0            0  Moderate                  Not known   
2                 1            1    Severe                         No   
3                 0            0      Mild                        Yes   
4                 1            0  Moderate                        Yes   

   Infected  
0         0  
1         1  
2         0  
3         1  
4         1

In [7]:
df.isna().sum()

Age                           0
Gender                        0
fever                         0
Bodypain                      0
Runny_nose                    0
Difficulty_in_breathing       0
Nasal_congestion              0
Sore_throat                   0
Severity                      0
Contact_with_covid_patient    0
Infected                      0
dtype: int64

In [8]:
pd.value_counts(df['Gender'])

Male           1257
Female         1208
Transgender      34
Name: Gender, dtype: int64

In [9]:
pd.value_counts(df['Severity'])

Mild        1591
Moderate     525
Severe       383
Name: Severity, dtype: int64

In [10]:
pd.value_counts(df['Contact_with_covid_patient'])

No           1203
Yes           638
Not known     633
yes            25
Name: Contact_with_covid_patient, dtype: int64

In [11]:
df['Contact_with_covid_patient'] = df['Contact_with_covid_patient'].str.lower()

In [12]:
pd.value_counts(df['Contact_with_covid_patient'])

no           1203
yes           663
not known     633
Name: Contact_with_covid_patient, dtype: int64

In [13]:
genderLabel = LabelEncoder()
gender = genderLabel.fit_transform(df['Gender'])

In [14]:
gender

array([1, 1, 2, ..., 0, 0, 0])

In [15]:
genderOneHot = OneHotEncoder()
gender = genderOneHot.fit_transform(gender.reshape(-1, 1))

In [16]:
gender

<2499x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2499 stored elements in Compressed Sparse Row format>

In [17]:
gender = gender.toarray()

In [18]:
gender

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [19]:
severityLabel = LabelEncoder()
severity = severityLabel.fit_transform(df['Severity'])

severityOneHot = OneHotEncoder()
severity = severityOneHot.fit_transform(severity.reshape(-1, 1)).toarray()

In [20]:
contactLabel = LabelEncoder()
contact = contactLabel.fit_transform(df['Contact_with_covid_patient'])

contactOneHot = OneHotEncoder()
contact = contactOneHot.fit_transform(contact.reshape(-1, 1)).toarray()

In [21]:
severity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [22]:
contact

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
df.drop(columns=['Gender', 'Severity', 'Contact_with_covid_patient'], inplace=True)

In [24]:
df.head()

Age  fever  Bodypain  Runny_nose  Difficulty_in_breathing  \
0   10    102         1           0                        0   
1   20    103         1           1                        0   
2   55     99         0           0                        0   
3   37    100         0           1                        1   
4   45    101         1           1                        1   

   Nasal_congestion  Sore_throat  Infected  
0                 0            1         0  
1                 0            0         1  
2                 1            1         0  
3                 0            0         1  
4                 1            0         1

In [25]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [26]:
X = np.c_[X, gender, severity, contact]

In [27]:
X[0]

array([ 10., 102.,   1.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   1.,
         0.,   0.,   1.,   0.,   0.])

In [28]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [32]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [33]:
y_pred = knn.predict(x_test)

In [34]:
accuracy_score(y_test, y_pred)

0.9424

In [35]:
confusion_matrix(y_test, y_pred)

array([[282,  17],
       [ 19, 307]], dtype=int64)

In [36]:
298 + 294

592

In [37]:
23 + 10

33

In [38]:
(298 + 294) / (298 + 294 + 23 + 10)

0.9472

In [39]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       299
           1       0.95      0.94      0.94       326

    accuracy                           0.94       625
   macro avg       0.94      0.94      0.94       625
weighted avg       0.94      0.94      0.94       625

