In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,50,15)

In [3]:
x

array([45, 24,  8, 33, 38, 10, 22, 49, 12, 22, 36, 29, 28, 16, 16])

In [4]:
x.shape

(15,)

In [5]:
np.shape(x)

(15,)

In [6]:
np.sum(x)

388

In [8]:
np.mean(x)

25.866666666666667

In [9]:
np.max(x)

49

In [10]:
np.min(x)

8

In [11]:
np.sort(x)

array([ 8, 10, 12, 16, 16, 22, 22, 24, 28, 29, 33, 36, 38, 45, 49])

In [12]:
np.std(x)

12.131868043389781

In [13]:
np.var(x)

147.1822222222222

In [15]:
np.reshape(x, (5,3))

array([[45, 24,  8],
       [33, 38, 10],
       [22, 49, 12],
       [22, 36, 29],
       [28, 16, 16]])

In [16]:
x.reshape(5,3)

array([[45, 24,  8],
       [33, 38, 10],
       [22, 49, 12],
       [22, 36, 29],
       [28, 16, 16]])

In [18]:
x = x.reshape(5,3)

In [19]:
x

array([[45, 24,  8],
       [33, 38, 10],
       [22, 49, 12],
       [22, 36, 29],
       [28, 16, 16]])

In [20]:
# convert n dimensional data to 1D
x = x.flatten()

In [21]:
x

array([45, 24,  8, 33, 38, 10, 22, 49, 12, 22, 36, 29, 28, 16, 16])

In [22]:
x = x.reshape(5,3)

In [23]:
x

array([[45, 24,  8],
       [33, 38, 10],
       [22, 49, 12],
       [22, 36, 29],
       [28, 16, 16]])

In [24]:
x.max()

49

In [25]:
# column wise
x.max(axis=0)

array([45, 49, 29])

In [26]:
# row wise
x.max(axis=1)

array([45, 38, 49, 36, 28])

In [27]:
x.sum()

388

In [28]:
x.sum(axis=0)

array([150, 163,  75])

In [29]:
x.sum(axis=1)

array([77, 81, 83, 87, 60])

In [32]:
y = np.random.randint(1,10,(5,3))

In [34]:
x,y

(array([[45, 24,  8],
        [33, 38, 10],
        [22, 49, 12],
        [22, 36, 29],
        [28, 16, 16]]),
 array([[6, 5, 4],
        [8, 4, 1],
        [7, 8, 2],
        [5, 2, 2],
        [8, 9, 6]]))

In [33]:
x + y

array([[51, 29, 12],
       [41, 42, 11],
       [29, 57, 14],
       [27, 38, 31],
       [36, 25, 22]])

In [35]:
# hstack - horizontal stack
# vstack - vertically stack
# c_  - column wise
# r_  - row wise
# concatenate - can be used for row or column

In [37]:
# adding a new column
y = np.array([[2],[4],[1],[5],[6]])
np.hstack((x,y))

array([[45, 24,  8,  2],
       [33, 38, 10,  4],
       [22, 49, 12,  1],
       [22, 36, 29,  5],
       [28, 16, 16,  6]])

In [40]:
# adding a new row
y = np.array([[8,5,3]])
x = np.vstack((x,y))

In [41]:
x

array([[45, 24,  8],
       [33, 38, 10],
       [22, 49, 12],
       [22, 36, 29],
       [28, 16, 16],
       [ 8,  5,  3]])

In [44]:
# alternative to hstack
z = np.random.randint(1,50,(6,1))
x = np.c_[x,z]

In [45]:
x

array([[45, 24,  8, 36],
       [33, 38, 10, 36],
       [22, 49, 12, 38],
       [22, 36, 29,  2],
       [28, 16, 16, 12],
       [ 8,  5,  3, 16]])

In [47]:
# alternative to vstack
z = np.random.randint(1,50,(1,4))
x = np.r_[x,z]

In [48]:
x

array([[45, 24,  8, 36],
       [33, 38, 10, 36],
       [22, 49, 12, 38],
       [22, 36, 29,  2],
       [28, 16, 16, 12],
       [ 8,  5,  3, 16],
       [15,  3, 30,  2]])

In [49]:
# filter data

In [50]:
x > 25

array([[ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [51]:
x[x > 25]

array([45, 36, 33, 38, 36, 49, 38, 36, 29, 28, 30])

In [53]:
# or condition
x[(x > 25) | (x == 2)]

array([45, 36, 33, 38, 36, 49, 38, 36, 29,  2, 28, 30,  2])

In [54]:
# and condition
x[(x > 25) & (x < 40)]

array([36, 33, 38, 36, 38, 36, 29, 28, 30])

In [55]:
np.where(x > 25, x ** 2, x)

array([[2025,   24,    8, 1296],
       [1089, 1444,   10, 1296],
       [  22, 2401,   12, 1444],
       [  22, 1296,  841,    2],
       [ 784,   16,   16,   12],
       [   8,    5,    3,   16],
       [  15,    3,  900,    2]])

In [56]:
x

array([[45, 24,  8, 36],
       [33, 38, 10, 36],
       [22, 49, 12, 38],
       [22, 36, 29,  2],
       [28, 16, 16, 12],
       [ 8,  5,  3, 16],
       [15,  3, 30,  2]])