In [1]:
import numpy as np

In [2]:
x = np.array([3,2,4,5,3])

In [3]:
x[0]

3

In [4]:
x[-1]

3

In [5]:
x[0:3]

array([3, 2, 4])

In [6]:
x = np.array([[23,21,13,14,7],[2,4,5,4,32],[5,3,3,6,67],[1,3,2,3,4],[4,3,32,4,6]])

In [7]:
x

array([[23, 21, 13, 14,  7],
       [ 2,  4,  5,  4, 32],
       [ 5,  3,  3,  6, 67],
       [ 1,  3,  2,  3,  4],
       [ 4,  3, 32,  4,  6]])

In [8]:
x[0]

array([23, 21, 13, 14,  7])

In [9]:
x[1]

array([ 2,  4,  5,  4, 32])

In [10]:
x[0][0]

23

In [11]:
x[1][0]

2

In [12]:
x[:]

array([[23, 21, 13, 14,  7],
       [ 2,  4,  5,  4, 32],
       [ 5,  3,  3,  6, 67],
       [ 1,  3,  2,  3,  4],
       [ 4,  3, 32,  4,  6]])

In [14]:
# will return 0th column
x[:, 0]

array([23,  2,  5,  1,  4])

In [15]:
x[:, 1]

array([21,  4,  3,  3,  3])

In [17]:
x[0:2]

array([[23, 21, 13, 14,  7],
       [ 2,  4,  5,  4, 32]])

In [18]:
x[0:3]

array([[23, 21, 13, 14,  7],
       [ 2,  4,  5,  4, 32],
       [ 5,  3,  3,  6, 67]])

In [19]:
x[:, 0]

array([23,  2,  5,  1,  4])

In [20]:
x[:, 0:2]

array([[23, 21],
       [ 2,  4],
       [ 5,  3],
       [ 1,  3],
       [ 4,  3]])

In [21]:
# will return 0th, 2nd and 3rd column
x[:, [0,2,3]]

array([[23, 13, 14],
       [ 2,  5,  4],
       [ 5,  3,  6],
       [ 1,  2,  3],
       [ 4, 32,  4]])

In [22]:
x[0:3, 0:2]

array([[23, 21],
       [ 2,  4],
       [ 5,  3]])