In [1]:
import numpy as np

In [2]:
# 1st way to create array
x1 = np.array([3,2,5,6,4])

In [3]:
x1

array([3, 2, 5, 6, 4])

In [4]:
x2 = np.array([34,4,2,3,5,"hello"])

In [5]:
x2

array(['34', '4', '2', '3', '5', 'hello'], dtype='<U11')

In [6]:
np.array([3,2,3,23,5,67,10.5])

array([ 3. ,  2. ,  3. , 23. ,  5. , 67. , 10.5])

In [7]:
np.array([3,2,3,23,5,67,10.5,'hello'])

array(['3', '2', '3', '23', '5', '67', '10.5', 'hello'], dtype='<U32')

In [8]:
np.array([3,2,3,23,5,67,True])

array([ 3,  2,  3, 23,  5, 67,  1])

In [9]:
x1[0]

3

In [11]:
x1[3]

6

In [12]:
# 2nd way
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [14]:
np.arange(1,51,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [15]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [16]:
# 3rd way
# linspace - linear space
# by defualt it will generate 50 elements in a given range with equal interval
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [17]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
np.linspace(1,10,num=20,retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [19]:
# 4th way
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# 5th way
np.random.random()

0.3121304522708682

In [26]:
np.random.random(5)

array([0.53289995, 0.04203529, 0.74936821, 0.5443469 , 0.17423082])

In [27]:
np.random.random([4,4])

array([[0.57284688, 0.89931102, 0.34730898, 0.4676876 ],
       [0.33445094, 0.09448413, 0.23807357, 0.99814164],
       [0.38088319, 0.56841633, 0.96809242, 0.56000865],
       [0.69515046, 0.85697236, 0.80904436, 0.21099903]])

In [30]:
# normal distribution
np.random.randn(3,3)

array([[ 0.38579941,  1.0675874 , -0.072371  ],
       [-1.6149796 , -0.54846345,  1.19866098],
       [-0.34353077,  0.29024701, -0.40978243]])

In [31]:
np.random.randint(1,10)

2

In [32]:
np.random.randint(1,10,5)

array([3, 6, 3, 2, 8])

In [33]:
np.random.randint(1,10,[5,5])

array([[7, 9, 1, 5, 7],
       [7, 6, 3, 4, 8],
       [3, 3, 4, 9, 4],
       [1, 4, 1, 7, 5],
       [9, 8, 6, 1, 1]])

In [36]:
np.random.seed(10)
np.random.randint(1,10,[5,5])

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]])

In [54]:
np.random.seed(4)
# Pseudo random
np.random.randint(1,10)

8